// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQVotjqp_tQoyx7Br05IDt_s92PRg8bk',
    appId: '1:215091015615:android:a79d3726323a81769cbb0a',
    messagingSenderId: '215091015615',
    projectId: 'todolist-4040b',
    storageBucket: 'todolist-4040b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdbZGDmHFfBeuTcytRnLFdNqjFyFTMvk',
    appId: '1:215091015615:ios:ff0c3609497174739cbb0a',
    messagingSenderId: '215091015615',
    projectId: 'todolist-4040b',
    storageBucket: 'todolist-4040b.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjaN7Bf5lZym3GE7WoRtI3aJCqDEoJyTw',
    appId: '1:215091015615:web:6ecdff01cc85fb389cbb0a',
    messagingSenderId: '215091015615',
    projectId: 'todolist-4040b',
    authDomain: 'todolist-4040b.firebaseapp.com',
    storageBucket: 'todolist-4040b.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwdbZGDmHFfBeuTcytRnLFdNqjFyFTMvk',
    appId: '1:215091015615:ios:ff0c3609497174739cbb0a',
    messagingSenderId: '215091015615',
    projectId: 'todolist-4040b',
    storageBucket: 'todolist-4040b.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjaN7Bf5lZym3GE7WoRtI3aJCqDEoJyTw',
    appId: '1:215091015615:web:a1bed3f5b8bcc51c9cbb0a',
    messagingSenderId: '215091015615',
    projectId: 'todolist-4040b',
    authDomain: 'todolist-4040b.firebaseapp.com',
    storageBucket: 'todolist-4040b.appspot.com',
  );

}